services:

  mongodb:
    image: mongo:latest
    container_name: patient-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_patient
      MONGO_INITDB_ROOT_PASSWORD: pass_patient
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /data/db